# Generated by Django 3.1 on 2021-07-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(default=None, max_length=30)),
                ('stock_id', models.CharField(default=None, max_length=14)),
                ('name', models.CharField(default=None, max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('sale_price', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
            ],
        ),
    ]
