# Generated by Django 3.1 on 2021-07-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('softdrinks', 'SOFTDRINKS'), ('snacks', 'SNACKS'), ('miscallaneous', 'Miscallaneous')], default='miscallaneous', max_length=15)),
                ('quantity', models.IntegerField(default=0)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.CharField(max_length=10)),
                ('products', models.JSONField()),
                ('selesDate', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
