# Generated by Django 3.1 on 2021-07-12 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.CharField(default='09321212072021', editable=False, max_length=14, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('softdrinks', 'SOFTDRINKS'), ('snacks', 'SNACKS'), ('miscallaneous', 'Miscallaneous')], default='miscallaneous', max_length=15)),
                ('quantity', models.IntegerField()),
                ('vendors', models.CharField(max_length=35)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('return_list', models.JSONField()),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(default='2021-07-06 14:39:50.140839+05', null=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.sale')),
            ],
        ),
    ]
